# Generated by Django 5.0 on 2023-12-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coden',
            field=models.CharField(max_length=255, verbose_name='Code Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculty', verbose_name='Faculties'),
        ),
        migrations.AlterField(
            model_name='course',
            name='inst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instructor', verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.level', verbose_name='Levels'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Instructor name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='aca_em',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Student Email'),
        ),
    ]
